version: 2
jobs:
  build:
    working_directory: ~/angularTesting
    docker:
      - image: circleci/node:10.5-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run test -- --no-watch --no-progress --
